baseURL = "https://distracted-wescoff-ddd45b.netlify.app/"
languageCode = "en-us"
title = "Dhaba Consulting"
[[menu.mainmenu]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 4
[[menu.mainmenu]]
identifier = "about"
name = "About"
url = "/about"
weight = 3
[[menu.mainmenu]]
identifier = "blog"
name = "Blogs"
url = "/blog/"
weight = 2
[[menu.mainmenu]]
identifier = "offerings"
name = "Offerings"
url = "/"
weight = 1
